# yaml 配置
version: '3.7'
services:
  web:
    build:
      context: ./NGINX
      dockerfile: Dockerfile
      labels: 
        - "com.jhvege.description=Portal webapp"
        - "com.jhvege.department=Finance"
        - "com.jhvege.label-with-empty-value"
    image: jhnginx:v4
    security_opt:
     - seccomp=/home/jhvege/KingVeg2015/jhvege/seccomp.json 
    ports:
     - "8088:80"
    container_name: jhnginxprod
    links:
      - php
    depends_on: 
      - db
      - php
    logging: 
      driver: json-file
      options:
        max-size: "200k" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    volumes:
      - jhdrupal:/usr/share/nginx
  db:
    build:
      context: ./DB
      dockerfile: Dockerfile
      labels: 
        - "com.jhvege.description=JHMysql"
        - "com.jhvege.department=Finance"
        - "com.jhvege.label-with-empty-value"
    logging: 
      driver: json-file
      options: 
        max-size: "200k" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    volumes:
         - jhmysql:/var/lib/mysql
    image: jhmysql:v3
    security_opt:
     - seccomp=/home/jhvege/KingVeg2015/jhvege/seccomp.json 
    expose:
      - "3306"
    container_name: jhmysqlprod
  php: 
    build: 
      context: ./PHP
      dockerfile: Dockerfile
      labels: 
        - "com.jhvege.description=JHPHP"
        - "com.jhvege.department=Finance"
        - "com.jhvege.label-with-empty-value"
    expose: 
       - "9000"
    links:
      - db
    logging: 
      driver: json-file
      options:
        max-size: "200k" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    image: jhphp:v4
    security_opt:
     - seccomp=/home/jhvege/KingVeg2015/jhvege/seccomp.json 
    container_name: jhphpprod
    hostname: localhost
    volumes:
      - jhdrupal:/usr/share/nginx
volumes:
  jhdrupal: {}
  jhmysql: {}

networks:
  default:
    driver: bridge
