#yaml 配置
version: '3.7'
services:
  web:
    image: ghcr.io/secosun/jhnginx:v1
    build:
      context: ./NGINX
      dockerfile: Dockerfile
      labels: 
        - "com.jhvege.description=Portal webapp"
        - "com.jhvege.department=Finance"
        - "com.jhvege.label-with-empty-value"
#    security_opt:
#     - seccomp=seccomp.json 
    ports:
     - "8088:80"
    container_name: jhnginxdev
    links:
      - php
    depends_on: 
      - db
      - php
    logging: 
      driver: json-file
      options:
        max-size: "200k" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    volumes:
      - jhdrupald7:/usr/share/nginx
  db:
    image: ghcr.io/secosun/jhmysql:v1
    build:
      context: ./DB
      dockerfile: Dockerfile
      labels: 
        - "com.jhvege.description=JHMysql"
        - "com.jhvege.department=Finance"
        - "com.jhvege.label-with-empty-value"
    logging: 
      driver: json-file
      options: 
        max-size: "200k" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    volumes:
         - jhmysqld7:/var/lib/mysql
#    security_opt:
#     - seccomp=seccomp.json 
    expose:
      - "3306"
    container_name: jhmysqldev
  php: 
    image: ghcr.io/secosun/jhphp:v1
    build: 
      context: ./PHP
      dockerfile: Dockerfile
      labels: 
        - "com.jhvege.description=JHPHP"
        - "com.jhvege.department=Finance"
        - "com.jhvege.label-with-empty-value"
    expose: 
       - "9000"
    links:
      - db
    logging: 
      driver: json-file
      options:
        max-size: "200k" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
 #   security_opt:
 #    - seccomp=seccomp.json 
    container_name: jhphdev
    hostname: localhost
    volumes:
      - jhdrupald7:/usr/share/nginx
volumes:
  jhdrupald7: {}
  jhmysqld7: {}

networks:
  default:
    driver: bridge
